events{}
http {
    include /etc/nginx/mime.types;
    server {
        listen 42724;
        server_name DrafterRDP;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
